name: My Workflow

on: workflow_dispatch

defaults:
  run:
    working-directory: environment/dev

jobs:
  terraform_init_plan:
    runs-on: self-hosted   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform plan
        run: terraform plan
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
  terraform_apply:
    runs-on: self-hosted
    needs: terraform_init_plan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
