name: My Workflow

on: workflow_dispatch

jobs:
  terraform:
    runs-on: self-hosted   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
 
